# This is a basic workflow to help you get started with Actions

name: Duplicate PR for RC branch
on:
  pull_request:
    types:
      - closed

jobs:
  create_pr:
    env:
      GH_TOKEN: ${{ github.token }}
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git status 
        git config --global user.email "${GITHUB_ACTOR}"
        git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
        git checkout -b sync/pr-${{ github.event.pull_request.number }}-to-rc
        gh pr diff --patch ${{ github.event.pull_request.number }} | git am
        git push -u origin sync/pr-${{ github.event.pull_request.number }}-to-rc
        gh pr create --base "rc/test" --title "Automated: PR #${{ github.event.pull_request.number }} to RC" --body "#${{ github.event.pull_request.number }}"
