# This is a basic workflow to help you get started with Actions

name: Duplicate PR for RC branch
on:
  pull_request:
    types:
      - closed

jobs:
  create_pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git status 
        git checkout -b sync/pr-{{ github.event.pull_request.id }}-to-rc
        gh pr diff --patch {{ github.event.pull_request.id }} | git am
        git push 
        gh pr create -b "#{{ github.event.pull_request.id }}"
