# This is a basic workflow to help you get started with Actions

name: Duplicate PR for RC branch
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  create_pr:
    name: Cherry-pick and create PR to RC branch 
    env:
      GH_TOKEN: ${{ github.token }}
      TAG_PREFIX: "staging_"
      RC_BRANCH_PREFIX: "rc/"
    if: |
      (github.event.pull_request.merged == true 
      && github.event.pull_request.base.ref == 'main'
      && contains(github.event.pull_request.labels.*.name, 'RC')
      ) 
      || (
      github.event.pull_request.merged == true 
      && github.event.pull_request.base.ref == 'main'
      && github.event.label.name == 'RC'
      )
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Find the latest ${{ env.TAG_PREFIX }}* tag
      run: |
        tag=$(git tag --sort=creatordate -l '${{ env.TAG_PREFIX }}*'| tail -1)
        echo "STAGING_TAG=$tag" >> $GITHUB_ENV
        echo "Staging tag: $tag"
    - name: Find the latest RC branch name
      run: |
        ref=$(git branch -a --contains $STAGING_TAG | grep -F "${{ env.RC_BRANCH_PREFIX }}" | awk -F 'remotes/origin/' '{print $2}' )
        echo "RC_BRANCH_REF=$ref" >> $GITHUB_ENV
        echo "RC BRANCH: $ref"
    - name: Check for RC branch existence
      run: |
         if [ "$RC_BRANCH_REF" != '' ]; then
            echo "Found RC branch $RC_BRANCH_REF"
          else
            echo "RC branch not found";
            exit 1;
          fi        
    - name: Create a branch and apply patch from PR
      id: patch
      run: |
          git status 
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout $RC_BRANCH_REF
          git checkout -b sync/pr-${{ github.event.pull_request.number }}-to-rc
          gh pr diff --patch ${{ github.event.pull_request.number }} | git am --whitespace=fix || echo ::set-output name=status::failure
      continue-on-error: true
    - name: Leave comment in case of failure
      if: steps.patch.outputs.status == 'failure'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "Failed to create a PR to RC branch, please do it manually" 
        exit 1
    
    - name: Push new branch and create a PR
      run: | 
          git push -u origin sync/pr-${{ github.event.pull_request.number }}-to-rc
          createPr() {
            gh pr create --base $RC_BRANCH_REF --title "Automated: PR #${{ github.event.pull_request.number }} to RC" --body "Changes from PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.body }}"
          }
          
          echo "PR_OUTPUT=$(createPr)" >> $GITHUB_ENV


    - name: Comment on success
      run: | 
        gh pr comment ${{ github.event.pull_request.number }} --body "Created pr to RC branch, please merge $PR_OUTPUT"
